import type { AITool, Category } from '@/types';

export const defaultCategories: Category[] = [
  { id: 'text-writing', name: 'Text & Writing', color: '#00D9FF' },
  { id: 'image-generation', name: 'Image Generation', color: '#FF6B6B' },
  { id: 'video-audio', name: 'Video & Audio', color: '#9B59B6' },
  { id: 'code-development', name: 'Code & Development', color: '#27AE60' },
  { id: 'research-tools', name: 'Research Tools', color: '#F39C12' },
  { id: 'marketing-sales', name: 'Marketing & Sales', color: '#E74C3C' },
  { id: 'productivity', name: 'Productivity', color: '#3498DB' },
  { id: 'automation', name: 'Automation', color: '#9B59B6' },
  { id: 'favorites', name: 'Favorites', color: '#E74C3C' },
];

export const defaultTools: AITool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chatgpt.com',
    category: 'Text & Writing',
    description: 'OpenAI\'s conversational AI assistant for general tasks and creative writing.',
    icon: 'MessageSquare',
    createdAt: Date.now(),
    order: 0,
  },
  {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    category: 'Text & Writing',
    description: 'Anthropic\'s AI assistant with strong reasoning and analysis capabilities.',
    icon: 'Brain',
    createdAt: Date.now() - 1000,
    order: 1,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    url: 'https://gemini.google.com',
    category: 'Text & Writing',
    description: 'Google\'s multimodal AI with integration across Google services.',
    icon: 'Sparkles',
    createdAt: Date.now() - 2000,
    order: 2,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    url: 'https://midjourney.com',
    category: 'Image Generation',
    description: 'AI-powered image generation through Discord with stunning artistic results.',
    icon: 'Image',
    createdAt: Date.now() - 3000,
    order: 3,
  },
  {
    id: 'dalle',
    name: 'DALL-E',
    url: 'https://openai.com/dall-e',
    category: 'Image Generation',
    description: 'OpenAI\'s image generation model for creating images from text descriptions.',
    icon: 'Palette',
    createdAt: Date.now() - 4000,
    order: 4,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    category: 'Code & Development',
    description: 'AI pair programmer that helps you write code faster.',
    icon: 'Code',
    createdAt: Date.now() - 5000,
    order: 5,
  },
  // 26 AI Tools for 2026
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    url: 'https://perplexity.ai',
    category: 'Research Tools',
    description: 'AI search engine that provides answers with cited sources.',
    icon: 'Search',
    createdAt: Date.now() - 6000,
    order: 6,
  },
  {
    id: 'descript',
    name: 'Descript',
    url: 'https://descript.com',
    category: 'Video & Audio',
    description: 'Edit video and audio by editing text like a document.',
    icon: 'FileText',
    createdAt: Date.now() - 6100,
    order: 7,
  },
  {
    id: 'jasper',
    name: 'Jasper AI',
    url: 'https://jasper.ai',
    category: 'Marketing & Sales',
    description: 'AI writing assistant for marketing copy that converts.',
    icon: 'PenTool',
    createdAt: Date.now() - 6200,
    order: 8,
  },
  {
    id: 'runway',
    name: 'Runway ML',
    url: 'https://runwayml.com',
    category: 'Video & Audio',
    description: 'Create stunning video effects and AI-generated content.',
    icon: 'Video',
    createdAt: Date.now() - 6300,
    order: 9,
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    url: 'https://elevenlabs.io',
    category: 'Video & Audio',
    description: 'Generate realistic voice clones and text-to-speech.',
    icon: 'Mic',
    createdAt: Date.now() - 6400,
    order: 10,
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    url: 'https://notion.so',
    category: 'Productivity',
    description: 'AI-powered workspace for notes, docs, and collaboration.',
    icon: 'Layout',
    createdAt: Date.now() - 6500,
    order: 11,
  },
  {
    id: 'otter',
    name: 'Otter.ai',
    url: 'https://otter.ai',
    category: 'Productivity',
    description: 'Transcribe meetings and conversations instantly.',
    icon: 'Mic2',
    createdAt: Date.now() - 6600,
    order: 12,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    url: 'https://copy.ai',
    category: 'Marketing & Sales',
    description: 'Write sales emails and marketing copy that sells.',
    icon: 'Mail',
    createdAt: Date.now() - 6700,
    order: 13,
  },
  {
    id: 'beautiful-ai',
    name: 'Beautiful.ai',
    url: 'https://beautiful.ai',
    category: 'Productivity',
    description: 'Design pitch decks and presentations automatically.',
    icon: 'Presentation',
    createdAt: Date.now() - 6800,
    order: 14,
  },
  {
    id: 'photoroom',
    name: 'Photoroom',
    url: 'https://photoroom.com',
    category: 'Image Generation',
    description: 'Remove backgrounds and edit photos perfectly.',
    icon: 'Camera',
    createdAt: Date.now() - 6900,
    order: 15,
  },
  {
    id: 'speechify',
    name: 'Speechify',
    url: 'https://speechify.com',
    category: 'Productivity',
    description: 'Turn text into audiobooks with natural voices.',
    icon: 'Headphones',
    createdAt: Date.now() - 7000,
    order: 16,
  },
  {
    id: 'chatpdf',
    name: 'ChatPDF',
    url: 'https://chatpdf.ai',
    category: 'Research Tools',
    description: 'Analyze PDF documents and get insights from AI.',
    icon: 'FileText',
    createdAt: Date.now() - 7100,
    order: 17,
  },
  {
    id: 'bardeen',
    name: 'Bardeen',
    url: 'https://bardeen.ai',
    category: 'Automation',
    description: 'Automate repetitive tasks and workflows.',
    icon: 'Zap',
    createdAt: Date.now() - 7200,
    order: 18,
  },
  {
    id: 'zapier',
    name: 'Zapier',
    url: 'https://zapier.com',
    category: 'Automation',
    description: 'Connect and automate all your apps and services.',
    icon: 'Link',
    createdAt: Date.now() - 7300,
    order: 19,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    url: 'https://writesonic.com',
    category: 'Text & Writing',
    description: 'Create blog posts, articles, and content fast.',
    icon: 'Edit3',
    createdAt: Date.now() - 7400,
    order: 20,
  },
  {
    id: 'lumen5',
    name: 'Lumen5',
    url: 'https://lumen5.com',
    category: 'Video & Audio',
    description: 'Turn blog posts into engaging videos.',
    icon: 'Film',
    createdAt: Date.now() - 7500,
    order: 21,
  },
  {
    id: 'fliki',
    name: 'Fliki',
    url: 'https://fliki.ai',
    category: 'Video & Audio',
    description: 'Generate videos from text with AI voices.',
    icon: 'Clapperboard',
    createdAt: Date.now() - 7600,
    order: 22,
  },
  {
    id: 'tome',
    name: 'Tome',
    url: 'https://tome.app',
    category: 'Productivity',
    description: 'Build storytelling presentations with AI.',
    icon: 'BookOpen',
    createdAt: Date.now() - 7700,
    order: 23,
  },
  {
    id: 'simplified',
    name: 'Simplified',
    url: 'https://simplified.com',
    category: 'Marketing & Sales',
    description: 'All-in-one content creation and design platform.',
    icon: 'Palette',
    createdAt: Date.now() - 7800,
    order: 24,
  },
  {
    id: 'vidyo',
    name: 'Vidyo.ai',
    url: 'https://vidyo.ai',
    category: 'Video & Audio',
    description: 'Repurpose long content into social media clips.',
    icon: 'Scissors',
    createdAt: Date.now() - 7900,
    order: 25,
  },
  {
    id: 'lexica',
    name: 'Lexica Art',
    url: 'https://lexica.art',
    category: 'Image Generation',
    description: 'Generate and search unique AI-generated images.',
    icon: 'Image',
    createdAt: Date.now() - 8000,
    order: 26,
  },
  {
    id: 'beatoven',
    name: 'Beatoven',
    url: 'https://beatoven.ai',
    category: 'Video & Audio',
    description: 'Create custom AI-generated soundtracks.',
    icon: 'Music',
    createdAt: Date.now() - 8100,
    order: 27,
  },
  {
    id: 'murf',
    name: 'Murf AI',
    url: 'https://murf.ai',
    category: 'Video & Audio',
    description: 'Produce professional voiceovers with AI.',
    icon: 'Volume2',
    createdAt: Date.now() - 8200,
    order: 28,
  },
  {
    id: 'fireflies',
    name: 'Fireflies',
    url: 'https://fireflies.ai',
    category: 'Productivity',
    description: 'Record, transcribe, and summarize meetings.',
    icon: 'Phone',
    createdAt: Date.now() - 8300,
    order: 29,
  },
  {
    id: 'chatbase',
    name: 'Chatbase',
    url: 'https://chatbase.co',
    category: 'Code & Development',
    description: 'Build custom AI chatbots for your website.',
    icon: 'Bot',
    createdAt: Date.now() - 8400,
    order: 30,
  },
  {
    id: 'genspark',
    name: 'Genspark',
    url: 'https://genspark.ai',
    category: 'Research Tools',
    description: 'Game-changing AI agent for complex tasks.',
    icon: 'Sparkles',
    createdAt: Date.now() - 8500,
    order: 31,
  },
];

export const iconOptions = [
  'MessageSquare',
  'Brain',
  'Sparkles',
  'Image',
  'Palette',
  'Code',
  'Search',
  'Zap',
  'Wand2',
  'Bot',
  'Cpu',
  'Globe',
  'Layers',
  'Box',
  'Terminal',
  'FileCode',
  'BookOpen',
  'GraduationCap',
  'Lightbulb',
  'Rocket',
  'Star',
  'Heart',
  'Bookmark',
  'ExternalLink',
  'FileText',
  'PenTool',
  'Video',
  'Mic',
  'Mic2',
  'Layout',
  'Mail',
  'Presentation',
  'Camera',
  'Headphones',
  'Link',
  'Edit3',
  'Film',
  'Clapperboard',
  'Scissors',
  'Music',
  'Volume2',
  'Phone',
];
